name: Docker image c2

on:
  push:
    paths:
      - 'c2/*'
      - 'c2/**'

jobs:
  build-c2-amd64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: amd64
      image: c2
      tag: latest
      base: oonray/c2:user
      context: c2
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
  build-c2-arm64:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      arch: arm64
      image: c2
      tag: arm64
      base: oonray/c2:user
      context: c2
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}


