#COMFY
name: Docker update image COMFY
on:
  push:
    paths:
      - 'comfy/*'
      - 'comfy/**'
      - '!comfy/compose/**'

jobs:
  build-comfy:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      image: comfy
      tag: latest
      base: oonray/comfy:base
      context: comfy
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
