#COMFY
name: Docker image COMFY base
on:
  push:
    paths:
      - 'base/comfy/*'
      - 'base/comfy/**'

jobs:
  build-comfy:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      image: comfy
      tag: base
      base: nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04
      context: comfy
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
