#DEV
name: Docker image Dev
on:
  push:
    paths:
      - 'base/dev/full/*'
      - 'base/dev/full/**'

jobs:
  build-base-dev:
    uses: oonray/Containers/.github/workflows/container.yml@main
    with:
      image: dev
      tag: base
      base: oonray/user-debian:latest
      context: base/dev/full
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
